spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: games_service
          uri: http://localhost:8081/games
          predicates:
            - Path=/games/v1/catalogue/list/**"
        - id: games_service
          uri: http://localhost:8081/games
          predicates:
            - Path=/games/v1/catalogue/**



        - id: cart_service
          uri: http://localhost:8083/cart
          predicates:
            - Path=/cart/v1/update
        - id: cart_service
          uri: http://localhost:8083/cart
          predicates:
            - Path=/cart/v1/content
        - id: cart_service
          uri: http://localhost:8083/cart
          predicates:
            - Path=/cart/v1/purchase/**



        - id: login_service
          uri: http://localhost:8082/login
          predicates:
            - Path=/login/v1/authorization
        - id: login_service
          uri: http://localhost:8082/login
          predicates:
            - Path=/login/v1/registration


eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


variables:
  webclient:
    timeout: 1000