spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    gateway:
      routes:
      - id: games_service
        uri: http://localhost:8081/games
        predicates:
        - Path=/games/getAll
      - id: games_service
        uri: http://localhost:8081/games
        predicates:
        - Path=/games/get/**
      - id: cart_service
        uri: http://localhost:8083/cart
        predicates:
        - Path=/cart/**

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/