version: "3.9"
services:

  #Eureka
  registry-service:
    build:
      context: ./server/registry-service
      dockerfile: Dockerfile
    ports:
      - 8700-8710:8761
    image: registry-service
    hostname: registry-service
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - private
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      start_period: 1s
      interval: 3s
      timeout: 6s
      retries: 3


  #Configuration-service
  config-service:
    build:
      context: ./server/config-service
      dockerfile: Dockerfile
    ports:
      - 8001-8010:8001
    image: config-service
    hostname: config-service
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - private
    depends_on:
      registry-service:
        condition: service_healthy


networks:
  private:
    driver: bridge
