version: "3.9"
services:
  config-service:
#    build: /home/sergey/work/spring/Fnd_games_store/server/config-service
    build:
      context: ./server/config-service
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    container_name: config-service-container
    image: config-service
    hostname: config-service
    networks:
      - private
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/actuator/health"]
      start_period: 1s
      interval: 3s
      timeout: 6s
      retries: 3

  #Eureka
#  registry-service:
#    build: /home/sergey/work/spring/Fnd_games_store/server/registry-service
#    ports:
#      - 8761:8761
#    container_name: registry-service
#    hostname: registry-service
#    links:
#      - "config-service"
#    depends_on:
#      config-service:
#        condition: service_healthy
#    networks:
#      - private

networks:
  private:
    driver: bridge
