eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  server:
    peer-node-read-timeout-ms: 500

server:
  port: 8761

