spring:
  profiles:
    active: "dev"
  application:
    name: games-service
  config:
    import: optional:configserver:http://localhost:8001
    fail-fast: true
    password: admin
    username: user

flyway:
    user: postgres
    password: root
    schemas: app-db
    url: jdbc:postgresql://localhost:5432/games_service_database
    locations: filesystem:db/migration