spring:
  cloud:
    gateway:
      routes:
      - id: games_service
        uri: http://localhost:8081/games
        predicates:
        - Path=/games/**

server:
   port: 8989

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/