spring:
   application:
      name: gateway-service
   cloud:
      gateway:
      discovery:
         locator:
            enabled: true
      routes:
         - id: games
#            eureka should locate the games-service
            uri: localhost:8081//games
            predicates:
            - Path=/games/**

server:
   port: 8989

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/