spring:
   application:
      name: gateway-service
   cloud:
      gateway:
      discovery:
         locator:
            enabled: true
      routes:
         - id: games
#            eureka should locate the games-service
            uri: lb://games-service
            predicates:
            - Path=/games/**

server:
   port: 8989