spring:
  profiles:
    active: dev
  application:
    name: config-service

server:
  port: 8001


eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/

