spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      server:
        git:
          uri: file://home/sergey/Idea-wokspace/games_store_development_environment_configurations
          skipSslValidation: true
