spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      server:
        git:
          uri: file://home/sergey/workspace-idea/games_store_environment_configurations
          skipSslValidation: true
