spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Friendly-neighborhood-development/games_store_environment_configurations
          skipSslValidation: true
