spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  jpa:
    flyway:
      enabled: true
      validate-on-migrate: true
    database: h2
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    database-platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
server:
  servlet:
    context-path: /login
  port: 8082

variables:
  security:
    access_secret: OTFBRjg3MUMwOUYxODlFNDc3NEQwNTAxMTg0M0M0NzI5QTczNDY1QUU4MTA5MUFERjZFNDIxNTk0QTZDOUYyQg==
    access_expiration: 90000000