spring:
  config:
    import: optional:configserver:http://localhost:8001
    fail-fast: true
    password: admin
    username: user
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis

variables:
  security:
    access_secret: OTFBRjg3MUMwOUYxODlFNDc3NEQwNTAxMTg0M0M0NzI5QTczNDY1QUU4MTA5MUFERjZFNDIxNTk0QTZDOUYyQg==
    access_expiration: 90000000