spring:
  profiles:
    active: "dev"
  cloud:
    config:
      #        usage of a git repository
      server:
        git:
          uri: https://github.com/Friendly-neighborhood-development/Games_Store_Configurations
          skipSslValidation: true
    #        usage of a local folder
    #     server:
    #        native:
    #          search-locations: classpath:/services
  security:
    user:
      password: admin

server:
  port: 8001




