spring:
  cloud:
    config:

      #        usage of a git repository
      server:
        git:
          uri: https://github.com/SergeyPodgorny/YML-Coinfigurations-storage
          skipSslValidation: true
    #        usage of a local folder
    #     server:
    #        native:
    #          search-locations: classpath:/services
    #   setting up profiels, for now it is default
    profiles:
      active: default
  security:
    user:
      password: admin

server:
  port: 8001


