spring:
  profiles:
    active: prod
server:
  port: 8001

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      default-label: prod
      server:
        git:
          uri: https://github.com/Friendly-neighborhood-development/Games_Store_Configurations
          skipSslValidation: true
  security:
    user:
      password: admin

---
# TODO need to configure fetching configurations for different environments depends on selected profile
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      default-label: prod
      server:
        git:
          uri: https://github.com/Friendly-neighborhood-development/Games_Store_Configurations
          skipSslValidation: true
  security:
    user:
      password: admin
