spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      default-label: main
      #        usage of a git repository
      server:
        git:
          uri: https://github.com/Friendly-neighborhood-development/Games_Store_Configurations
          skipSslValidation: true

    #        usage of a local folder
    #     server:
    #        native:
    #          search-locations: classpath:/services
  security:
    user:
      password: admin

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      default-label: prod
      #        usage of a git repository
      server:
        git:
          uri: https://github.com/Friendly-neighborhood-development/Games_Store_Configurations
          skipSslValidation: true

    #        usage of a local folder
    #     server:
    #        native:
    #          search-locations: classpath:/services
  security:
    user:
      password: admin
