spring:
#  cache:
#    cache-names: games_catalogue_cache
#    cafeine:
#      spec: maximumSize=500,expireAfterAccess=600s
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  jpa:
    flyway:
      enabled: true
      validate-on-migrate: true
    database: h2
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    properties:
  datasource:
    database-platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
server:
  servlet:
    context-path: /games
  port: 8081

#flyway:
#    user: sa
#    password:
#    schemas: app-db
#    url: jdbc:h2:mem:testdb
#    locations: filesystem:db/migration